#http://www.easics.com/webtools/crctool
#
#
crc5:
	./crc_gen verilog 8 5 05
crc16:
	./crc_gen verilog 8 16 8005
crc32:
	./crc_gen verilog 32 32 02608edb 

crc8_spi:
	./crc_gen verilog 24 8 1D 
crc8_i2c:
	./crc_gen verilog 32 8 1D 

